---
---
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: add-owner-annotation
spec:
  match:
    scope: Namespaced
    namespaces: ["dev-apps"]
    kinds:
    - apiGroups: ["*"]
      kinds: ["*"]
  location: "metadata.annotations.owner"
  parameters:
    assign:
      value: "iamtheowner"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-privileged-false
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    namespaces: ["dev-apps"]
  location: "spec.containers[name:*].securityContext.privileged"
  parameters:
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: remove-err-logging
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.containers[name: *].args"
  parameters:
    operation: prune
    values:
      fromList:
        - --alsologtostderr
---