apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8stest
metadata:
  name: k8stest
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    namespaces: ["default"]
  parameters:
    labels: ["dummy"]
