apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: configmap-manager
spec:
  generateExistingOnPolicyUpdate: true
  validationFailureAction: enforce
  # failurePolicy: Fail
  # webhookTimeoutSeconds: 30
  rules:
  - name: generate-configmap
    match:
      all:
      - resources:
          kinds:
          - Namespace
          names:
          - dev-apps
    generate:
      synchronize: true
      apiVersion: v1
      kind: ConfigMap
      name: "{{request.object.metadata.name}}"
      namespace: "{{request.object.metadata.name}}"
      data:
        data:
          test: test
